# Site settings
author: Matthew Robinson 
title:  My Coding Journey. 
header-img: img/home-bg.png
email: matt_robinson1@yahoo.com
copyright_name: Matthew Robinson 
description: > # this means to ignore newlines until "baseurl:"
  Every mile builds endurance. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  MattRob77

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
